FROM python:3.11.3

WORKDIR /async_tests

RUN apt-get update && apt-get install -y iputils-ping
WORKDIR /tests

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# COPY ./requirements.txt ./requirements.txt

COPY . .

# COPY init.sh /

RUN chmod +x /init.sh

RUN  pip install --upgrade pip \
     && pip install -r requirements.txt --no-cache-dir

ENTRYPOINT ["/init.sh"]